/* TYPES CUSTOMER */
export const SEND_CUSTOMER_START = "SEND_CUSTOMER_START";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const SEND_CUSTOMER_FAIL = "SEND_CUSTOMER_FAIL";
export const CLEAR_MESSAGE_CUSTOMER = "CLEAR_MESSAGE_CUSTOMER";
export const CLEAR_ERRORS_CUSTOMER = "CLEAR_ERRORS_CUSTOMER";
