/* TYPES CUSTOMER */
export const SEND_CUSTOMER_START = "SEND_CUSTOMER_START";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_DTO_SUCCESS = "FETCH_CUSTOMER_DTO_SUCCESSS";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const SEND_CUSTOMER_FAIL = "SEND_CUSTOMER_FAIL";
export const CLEAR_MESSAGE_CUSTOMER = "CLEAR_MESSAGE_CUSTOMER";
export const CLEAR_ERRORS_CUSTOMER = "CLEAR_ERRORS_CUSTOMER";

/* TYPES TYPE_ITEMS */
export const SEND_TYPE_ITEM_START = "SEND_TYPE_ITEM_START";
export const FETCH_TYPE_ITEM_SUCCESS = "FETCH_TYPE_ITEM_SUCCESS";
export const CREATE_TYPE_ITEM_SUCCESS = "CREATE_TYPE_ITEM_SUCCESS";
export const UPDATE_TYPE_ITEM_SUCCESS = "UPDATE_TYPE_ITEM_SUCCESS";
export const DELETE_TYPE_ITEM_SUCCESS = "DELETE_TYPE_ITEM_SUCCESS";
export const SEND_TYPE_ITEM_FAIL = "SEND_TYPE_ITEM_FAIL";
export const CLEAR_MESSAGE_TYPE_ITEM = "CLEAR_MESSAGE_TYPE_ITEM";
export const CLEAR_ERRORS_TYPE_ITEM = "CLEAR_ERRORS_TYPE_ITEM";

/* TYPES ITEMS */
export const SEND_ITEM_START = "SEND_ITEM_START";
export const FETCH_ITEM_SUCCESS = "FETCH_ITEM_SUCCESS";
export const FETCH_ITEM_DTO_SUCCESS = "FETCH_ITEM_DTO_SUCCESS";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const SEND_ITEM_FAIL = "SEND_ITEM_FAIL";
export const CLEAR_MESSAGE_ITEM = "CLEAR_MESSAGE_ITEM";
export const CLEAR_ERRORS_ITEM = "CLEAR_ERRORS_ITEM";

/* TYPES CONTRACTS */
export const SEND_CONTRACT_START = "SEND_CONTRACT_START";
export const FETCH_CONTRACT_SUCCESS = "FETCH_CONTRACT_SUCCESS";
export const CREATE_CONTRACT_SUCCESS = "CREATE_CONTRACT_SUCCESS";
export const UPDATE_CONTRACT_SUCCESS = "UPDATE_CONTRACT_SUCCESS";
export const SEND_CONTRACT_FAIL = "SEND_CONTRACT_FAIL";
export const CLEAR_MESSAGE_CONTRACT = "CLEAR_MESSAGE_CONTRACT";
export const CLEAR_ERRORS_CONTRACT = "CLEAR_ERRORS_CONTRACT";
